on:
  workflow_dispatch:
    inputs:
      level:
        description: 'level to be executed'
        required: true
        default: 'staging'
        type: choice
        options:
        - dev
        - staging
        - prod

jobs: 

  run-test-job:

    runs-on: ubuntu-latest

    steps:
      - name: test

        run: |-
          echo "the level is: ${{ github.event.inputs.level}}"